server:
  port: 9098

spring:
  application:
    name: food-service
  datasource:
    url: jdbc:mysql://localhost:3306/fooddb
    username: vinay
    password: "{cipher}398ed2e495f44b20d1ab0c449dacde8c528bd8e219fd127cff498e55d1545cbf"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

info:
  app:
    name: "Food Service"
    description: "This is food service. we are in production right now"
    version: "1.0 Production"
